[GeneralSimulationParameters]
# simulation name which defines group name
simulationname = "sim1"
# resolution in mts
resolution = [180.0, 300.0]
level2precision = [0.005]   # corresponds to 0.5%
# gas to be simulated
gas = "CO2"
# output file location: output file will be based on the name of gas
outputfile = "/home/manu/Downloads/Down"

[GeneralSimulationParameters.NO2toCO2]
# NO2 to co2 conversion
nox_to_co2 = 0.001
absoluteerror = 5E19
relativeerror = 0.25
flag = false

[PlumeData]
inputdatafilename = "../data/Microhh_CO2.h5"

[LSQ]
[LSQ.Level4Precision]
# flag for absolute threshold or relative one
emission = [1.4, 6, 0.2]  # in MT/y [start, end, step] 
numberofpixels = 7